<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pesanan;

class PesananSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // === JANUARI 2026 (Total: ~Rp 5.095.000) ===
            [
                'kode_pesanan' => 'ORD-2026-001',
                'nama_pelanggan' => 'Budi Santoso',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '2 Pcs (3x1 meter)',
                'total_harga' => 150000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-01-08',
                'catatan_finishing' => 'Mata Ayam 4 Sudut',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-002',
                'nama_pelanggan' => 'PT Jaya Mandiri',
                'nama_produk' => 'Brosur A4 Full Color',
                'jumlah_ukuran' => '15 Rim',
                'total_harga' => 2250000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-01-14',
                'catatan_finishing' => 'Lipat 3, Potong Pas',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-003',
                'nama_pelanggan' => 'Siti Aminah',
                'nama_produk' => 'Kartu Nama Exclusive',
                'jumlah_ukuran' => '6 Box',
                'total_harga' => 270000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-01-18',
                'catatan_finishing' => 'Laminasi Doff',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-004',
                'nama_pelanggan' => 'CV Abadi Karya',
                'nama_produk' => 'Kalender Meja 2026',
                'jumlah_ukuran' => '35 Pcs',
                'total_harga' => 1925000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-01-22',
                'catatan_finishing' => 'Jilid Spiral Kawat',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-005',
                'nama_pelanggan' => 'Dewi Lestari',
                'nama_produk' => 'Stiker Vinyl Cutting',
                'jumlah_ukuran' => '15 Sheet A3+',
                'total_harga' => 525000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-01-28',
                'catatan_finishing' => 'Kiss Cut, Laminasi Glossy',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],

            // === FEBRUARI 2026 (Total: ~Rp 7.850.000) ===
            [
                'kode_pesanan' => 'ORD-2026-006',
                'nama_pelanggan' => 'PT Jaya Mandiri',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '8 Pcs (4x1.5 meter)',
                'total_harga' => 1200000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-02-04',
                'catatan_finishing' => 'Mata Ayam 6 Lubang',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-007',
                'nama_pelanggan' => 'Resto Sedap Rasa',
                'nama_produk' => 'Brosur A4 Full Color',
                'jumlah_ukuran' => '20 Rim',
                'total_harga' => 3000000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-02-10',
                'catatan_finishing' => 'Lipat 2, Kertas Art Paper 150gr',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-008',
                'nama_pelanggan' => 'Budi Santoso',
                'nama_produk' => 'Stiker Vinyl Cutting',
                'jumlah_ukuran' => '40 Sheet A3+',
                'total_harga' => 1400000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-02-15',
                'catatan_finishing' => 'Die Cut Tembus',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-009',
                'nama_pelanggan' => 'Siti Aminah',
                'nama_produk' => 'Kartu Nama Exclusive',
                'jumlah_ukuran' => '10 Box',
                'total_harga' => 450000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-02-21',
                'catatan_finishing' => 'Laminasi Doff + Spot UV',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-010',
                'nama_pelanggan' => 'CV Abadi Karya',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '12 Pcs (3x1 meter)',
                'total_harga' => 1800000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-02-26',
                'catatan_finishing' => 'Selongsong Atas-Bawah',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],

            // === MARET 2026 (Total: ~Rp 10.950.000) ===
            [
                'kode_pesanan' => 'ORD-2026-011',
                'nama_pelanggan' => 'Yayasan Bina Insani',
                'nama_produk' => 'Brosur A4 Full Color',
                'jumlah_ukuran' => '25 Rim',
                'total_harga' => 3750000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-03-05',
                'catatan_finishing' => 'Lipat 3, Full Color',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-012',
                'nama_pelanggan' => 'PT Jaya Mandiri',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '15 Pcs (5x2 meter)',
                'total_harga' => 3750000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-03-12',
                'catatan_finishing' => 'Mata Ayam Tiap 50cm',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-013',
                'nama_pelanggan' => 'Dewi Lestari',
                'nama_produk' => 'Kartu Nama Exclusive',
                'jumlah_ukuran' => '12 Box',
                'total_harga' => 540000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-03-18',
                'catatan_finishing' => 'Laminasi Glossy',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-014',
                'nama_pelanggan' => 'Toko Berkah Mandiri',
                'nama_produk' => 'Stiker Vinyl Cutting',
                'jumlah_ukuran' => '50 Sheet A3+',
                'total_harga' => 1750000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-03-24',
                'catatan_finishing' => 'Laminasi Doff, Kiss Cut',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-015',
                'nama_pelanggan' => 'Budi Santoso',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '6 Pcs (3x2 meter)',
                'total_harga' => 1160000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-03-29',
                'catatan_finishing' => 'Mata Ayam 4 Sudut',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],

            // === APRIL 2026 (Total: ~Rp 9.200.000) ===
            [
                'kode_pesanan' => 'ORD-2026-016',
                'nama_pelanggan' => 'CV Abadi Karya',
                'nama_produk' => 'Brosur A4 Full Color',
                'jumlah_ukuran' => '18 Rim',
                'total_harga' => 2700000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-04-06',
                'catatan_finishing' => 'Lipat Pas',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-017',
                'nama_pelanggan' => 'dr. Hendra Kurniawan',
                'nama_produk' => 'Kartu Nama Exclusive',
                'jumlah_ukuran' => '8 Box',
                'total_harga' => 360000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-04-12',
                'catatan_finishing' => 'Laminasi Doff',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-018',
                'nama_pelanggan' => 'PT Jaya Mandiri',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '14 Pcs (4x1 meter)',
                'total_harga' => 2100000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-04-17',
                'catatan_finishing' => 'Selongsong Kiri-Kanan',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-019',
                'nama_pelanggan' => 'Resto Sedap Rasa',
                'nama_produk' => 'Stiker Vinyl Cutting',
                'jumlah_ukuran' => '70 Sheet A3+',
                'total_harga' => 2450000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-04-22',
                'catatan_finishing' => 'Laminasi Glossy Waterproof',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-020',
                'nama_pelanggan' => 'Siti Aminah',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '6 Pcs (3x1 meter)',
                'total_harga' => 1590000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-04-28',
                'catatan_finishing' => 'Mata Ayam 4 Sudut',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],

            // === MEI 2026 (Total: ~Rp 13.850.000) ===
            [
                'kode_pesanan' => 'ORD-2026-021',
                'nama_pelanggan' => 'Yayasan Bina Insani',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '18 Pcs (4x1.5 meter)',
                'total_harga' => 2700000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-05-04',
                'catatan_finishing' => 'Mata Ayam Keliling',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-022',
                'nama_pelanggan' => 'PT Jaya Mandiri',
                'nama_produk' => 'Brosur A4 Full Color',
                'jumlah_ukuran' => '30 Rim',
                'total_harga' => 4500000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-05-11',
                'catatan_finishing' => 'Lipat 3, Kertas 150gr Art Paper',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-023',
                'nama_pelanggan' => 'Toko Berkah Mandiri',
                'nama_produk' => 'Stiker Vinyl Cutting',
                'jumlah_ukuran' => '85 Sheet A3+',
                'total_harga' => 2975000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-05-17',
                'catatan_finishing' => 'Kiss Cut Lembaran',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-024',
                'nama_pelanggan' => 'CV Abadi Karya',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '16 Pcs (5x1 meter)',
                'total_harga' => 2600000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-05-23',
                'catatan_finishing' => 'Mata Ayam 8 Lubang',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-025',
                'nama_pelanggan' => 'Budi Santoso',
                'nama_produk' => 'Kartu Nama Exclusive',
                'jumlah_ukuran' => '24 Box',
                'total_harga' => 1080000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-05-29',
                'catatan_finishing' => 'Laminasi Doff 2 Sisi',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],

            // === JUNI 2026 (Total: ~Rp 16.410.000) ===
            [
                'kode_pesanan' => 'ORD-2026-026',
                'nama_pelanggan' => 'PT Jaya Mandiri',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '22 Pcs (6x2 meter)',
                'total_harga' => 6600000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-06-03',
                'catatan_finishing' => 'Keling Pinggir Keliling',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-027',
                'nama_pelanggan' => 'Resto Sedap Rasa',
                'nama_produk' => 'Brosur A4 Full Color',
                'jumlah_ukuran' => '25 Rim',
                'total_harga' => 3750000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-06-10',
                'catatan_finishing' => 'Potong Pas, Lipat 2',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-028',
                'nama_pelanggan' => 'Dewi Lestari',
                'nama_produk' => 'Stiker Vinyl Cutting',
                'jumlah_ukuran' => '90 Sheet A3+',
                'total_harga' => 3150000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-06-16',
                'catatan_finishing' => 'Die Cut Bentuk Custom',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-029',
                'nama_pelanggan' => 'CV Abadi Karya',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '12 Pcs (4x1.5 meter)',
                'total_harga' => 2100000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-06-22',
                'catatan_finishing' => 'Mata Ayam 4 Sudut',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-030',
                'nama_pelanggan' => 'Siti Aminah',
                'nama_produk' => 'Kartu Nama Exclusive',
                'jumlah_ukuran' => '18 Box',
                'total_harga' => 810000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-06-27',
                'catatan_finishing' => 'Laminasi Doff Premium',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],

            // === JULI 2026 (Total: ~Rp 19.950.000) ===
            [
                'kode_pesanan' => 'ORD-2026-031',
                'nama_pelanggan' => 'Yayasan Bina Insani',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '28 Pcs (4x1 meter)',
                'total_harga' => 4200000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-07-04',
                'catatan_finishing' => 'Selongsong Atas-Bawah',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-032',
                'nama_pelanggan' => 'PT Jaya Mandiri',
                'nama_produk' => 'Brosur A4 Full Color',
                'jumlah_ukuran' => '40 Rim',
                'total_harga' => 6000000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-07-11',
                'catatan_finishing' => 'Lipat 3, Brosur Profil Bisnis',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-033',
                'nama_pelanggan' => 'Toko Berkah Mandiri',
                'nama_produk' => 'Stiker Vinyl Cutting',
                'jumlah_ukuran' => '120 Sheet A3+',
                'total_harga' => 4200000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-07-17',
                'catatan_finishing' => 'Laminasi Glossy Tebal',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-034',
                'nama_pelanggan' => 'CV Abadi Karya',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '25 Pcs (3x1.5 meter)',
                'total_harga' => 4500000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-07-24',
                'catatan_finishing' => 'Mata Ayam 6 Lubang',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-035',
                'nama_pelanggan' => 'dr. Hendra Kurniawan',
                'nama_produk' => 'Kartu Nama Exclusive',
                'jumlah_ukuran' => '23 Box',
                'total_harga' => 1050000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-07-30',
                'catatan_finishing' => 'Laminasi Doff 2 Sisi',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],

            // === AGUSTUS 2026 (Total: ~Rp 24.690.000) ===
            [
                'kode_pesanan' => 'ORD-2026-036',
                'nama_pelanggan' => 'PT Jaya Mandiri',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '35 Pcs (5x1.5 meter)',
                'total_harga' => 6560000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-08-02',
                'catatan_finishing' => 'Mata Ayam Tiap 1 Meter',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-037',
                'nama_pelanggan' => 'Yayasan Bina Insani',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '24 Pcs (3x1 meter)',
                'total_harga' => 2880000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-08-08',
                'catatan_finishing' => 'Spanduk HUT RI Kemerdekaan',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-038',
                'nama_pelanggan' => 'Resto Sedap Rasa',
                'nama_produk' => 'Brosur A4 Full Color',
                'jumlah_ukuran' => '35 Rim',
                'total_harga' => 5250000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-08-14',
                'catatan_finishing' => 'Lipat 3, Kertas 150gr',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-039',
                'nama_pelanggan' => 'Toko Berkah Mandiri',
                'nama_produk' => 'Stiker Vinyl Cutting',
                'jumlah_ukuran' => '140 Sheet A3+',
                'total_harga' => 4900000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-08-19',
                'catatan_finishing' => 'Kiss Cut Label Produk',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-040',
                'nama_pelanggan' => 'CV Abadi Karya',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '20 Pcs (4x2 meter)',
                'total_harga' => 4000000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-08-25',
                'catatan_finishing' => 'Mata Ayam Sudut & Tengah',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-041',
                'nama_pelanggan' => 'Budi Santoso',
                'nama_produk' => 'Kartu Nama Exclusive',
                'jumlah_ukuran' => '24 Box',
                'total_harga' => 1100000,
                'status' => 'Selesai',
                'tanggal_pesan' => '2026-08-29',
                'catatan_finishing' => 'Laminasi Doff Elegan',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],

            // === SEPTEMBER 2026 (Total: ~Rp 28.300.000) ===
            [
                'kode_pesanan' => 'ORD-2026-042',
                'nama_pelanggan' => 'PT Jaya Mandiri',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '40 Pcs (5x2 meter)',
                'total_harga' => 10000000,
                'status' => 'Sedang Dicetak',
                'tanggal_pesan' => '2026-09-02',
                'catatan_finishing' => 'Bahan Korea 440gr, Mata Ayam 12 Titik',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-043',
                'nama_pelanggan' => 'Yayasan Bina Insani',
                'nama_produk' => 'Brosur A4 Full Color',
                'jumlah_ukuran' => '45 Rim',
                'total_harga' => 6750000,
                'status' => 'Finishing',
                'tanggal_pesan' => '2026-09-05',
                'catatan_finishing' => 'Potong Pas, Lipat 3 Brosur Donasi',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-044',
                'nama_pelanggan' => 'Resto Sedap Rasa',
                'nama_produk' => 'Stiker Vinyl Cutting',
                'jumlah_ukuran' => '150 Sheet A3+',
                'total_harga' => 5250000,
                'status' => 'Siap Diambil',
                'tanggal_pesan' => '2026-09-08',
                'catatan_finishing' => 'Vinyl Waterproof Glossy Tahan Minyak',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-045',
                'nama_pelanggan' => 'CV Abadi Karya',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '25 Pcs (3x1.5 meter)',
                'total_harga' => 3750000,
                'status' => 'Sedang Dicetak',
                'tanggal_pesan' => '2026-09-10',
                'catatan_finishing' => 'Mata Ayam 4 Sudut',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-046',
                'nama_pelanggan' => 'Dewi Lestari',
                'nama_produk' => 'Kartu Nama Exclusive',
                'jumlah_ukuran' => '30 Box',
                'total_harga' => 1350000,
                'status' => 'Antrean Cetak',
                'tanggal_pesan' => '2026-09-11',
                'catatan_finishing' => 'Laminasi Doff 2 Sisi + Box Akrilik',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
            [
                'kode_pesanan' => 'ORD-2026-047',
                'nama_pelanggan' => 'Toko Berkah Mandiri',
                'nama_produk' => 'Spanduk / Banner Flexi',
                'jumlah_ukuran' => '8 Pcs (4x1 meter)',
                'total_harga' => 1200000,
                'status' => 'Antrean Cetak',
                'tanggal_pesan' => '2026-09-12',
                'catatan_finishing' => 'Selongsong Atas-Bawah',
                'status_pembayaran' => 'Lunas',
                'sisa_bayar' => 0,
            ],
        ];

        foreach ($data as $item) {
            Pesanan::updateOrCreate(['kode_pesanan' => $item['kode_pesanan']], $item);
        }
    }
}
